- lua/mason-nvim-dap/mappings/configurations.lua
This lets `nvim-dap` automatically detect if a python virtual environment is activated and uses it rather than the system installation of python. This also aligns with how `pyright` and python LSP behaves
> bugfix(python): use virtual environment if activated

- lua/mason-nvim-dap/automatic_setup.lua
- lua/mason-nvim-dap/mappings/filetypes.lua
- lua/mason-nvim-dap/settings.lua
First of all, thank you for this plugin, it greatly reduced my config size.
Use case:
I used `simrat39/rust-tools.nvim` and would like it to configure my dap instead of `mason-nvim-dap.nvim`.
Solution:
This PR allow me to do things like:
```lua
require('mason-nvim-dap').setup {
automatic_setup = { filetypes = { codelldb = { 'c', 'cpp' } } },
}
``` 
This way I don't have to override the entire handler for codelldb and still let `mason-nvim-dap.nvim` configure c and cpp for me.
> feat: support overriding filetypes for adapters

- lua/mason-nvim-dap/mappings/configurations.lua
On windows, `HOME` environment variable doesn't exist, hence `os.getenv('HOME')` will return nil which causes `attempt to concatenate a nil value`.
This PR fixes that with an best effort guess of flutter's installation path on windows. A more sophisticated approach would be to find the install path dynamically from `$PATH` if required, something similar to what [flutter-tools.nvim](https://github.com/akinsho/flutter-tools.nvim/blob/ae0be3cef35c0cb41d6c7f814a19b3402d50fd7a/lua/flutter-tools/executable.lua#L18) do. Thought i'd imagine that would require some refactoring though.
> Fix dart & flutter path on windows

- lua/mason-nvim-dap/mappings/adapters.lua
Mason.nvim utilizes symlinks to organize package files. On Windows symlink support is complicated and so mason chooses to use .cmd script files to simplify things. Setting "command" to "codelldb" will only look for files with the name "codelldb", i.e. it will not find "codelldb.cmd".
This commit changes "command" to use vim.fn.exepath() which seems to find any executable file with an equivalent stem. This means it will find both files "codelldb" and "codelldb.cmd".
> fix(codelldb): use vim.fn.exepath for command (#51)

- lua/mason-nvim-dap/mappings/adapters.lua
Fixes #51 in the same manner as #52 but for all other adapters.
Tested on Windows with `cpptools` and it works as expected.
> fix: use vim.fn.exepath for all adapter commands

- README.md
Added instructions in the README for how to use mason-nvim-dap with Lazy.nvim as a package manager.
> docs: add installation instructions for lazy.nvim

- README.md
- lua/mason-nvim-dap/automatic_setup.lua
- lua/mason-nvim-dap/ensure_installed.lua
- lua/mason-nvim-dap/init.lua
- lua/mason-nvim-dap/mappings/adapters.lua
- lua/mason-nvim-dap/mappings/configurations.lua
- lua/mason-nvim-dap/mappings/filetypes.lua
- lua/mason-nvim-dap/settings.lua
----
Migration Guide:
1. Move `setup_handlers` table to `setup({handlers = TABLE})`.
2. To disable `automatic_setup`, provide an empty function to `handlers` like `handlers = {function() end,}`
3. Overriding configuration per adapter needs to be done in the handler table now
> feat!: 2.0

- README.md
* stress the need to call default_setup(config) in overrides
* mention that the fallback handler is a list element in text not just as code comment
* grammar improvements
---
In line 146 it says "It can also do that during runtime.". It is not obvious how to do this, as you'd only call setup() once, and pass the handlers table to it as an argument. Maybe you could explain this in a bit more detail?
> docs: improve handlers table doc + setup_handlers() migration notes

- lua/mason-nvim-dap/api/command.lua
The package `mason.mappings.language` does not exists and is always raising the
error:
```
  Error  09:11:32 msg_show.lua_error   DapInstall delve Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:45: Vim:Error executing Lua callback: ...y/mason-nvim-dap.nvim/lua/mason-nvim-dap/api/command.lua:12: module 'mason.mappings.language' not found:
no field package.preload['mason.mappings.language']
cache_loader: module mason.mappings.language not found
cache_loader_lib: module mason.mappings.language not found
no file './mason/mappings/language.lua'
no file '/usr/local/share/luajit-2.1.0-beta3/mason/mappings/language.lua'
no file '/usr/local/share/lua/5.1/mason/mappings/language.lua'
no file '/usr/local/share/lua/5.1/mason/mappings/language/init.lua'
no …
```
> fix: remove not used language_mappings defition

- lua/mason-nvim-dap/mappings/adapters/haskell.lua
- lua/mason-nvim-dap/mappings/configurations.lua
- lua/mason-nvim-dap/mappings/filetypes.lua
- lua/mason-nvim-dap/mappings/source.lua
Hi there,
I made a pull onto mason-registry to add haskell-debug-adapter so now we should be able to integrate it!
The default setup basically exactly what nvim-dap recommends. It should all be good, not sure entirely if it will work on windows as we had some errors with mason-registry with windows being funky but hopefully it's ok.
Please do comment on any changes that I could make, I would really appreciate any feedback.
> feat: Add haskell to list of supported debug adapters

- lua/mason-nvim-dap/mappings/configurations.lua
Hi again,
To test that everything was OK one last time. I did a fresh install of stack and everything without configuration. I found that I was unable to get the debug adapter to work. I realized that with a fresh install of ghcup, stack, and ghci, the prompt for ghci is now 'ghci>'. 
The fact that the haskell-debug-adapter is dependent on the prompt is a design flaw in my opinion. However setting the default value as the freshly-installed value should be fine for now.
> fix: changed default prompt to be the fresh-installed stack version

- lua/mason-nvim-dap/mappings/configurations.lua
Hi again,
I'm really sorry to be making so many pull requests, but I had a conversation with the author of the haskell-debug-adapter and came to the conclusion that it may be good to remove any potential user cofiguration from stalling the initialisation stage of teh debugger. We now use -ignore-dot-ghci to ensure ghci runs completely "fresh".
We now also use ghci-dap as the ghc engine, which makes debugging more convenient.
> fix: use ghci-dap and -ignore-dot-ghci

- lua/mason-nvim-dap/mappings/adapters/codelldb.lua
- lua/mason-nvim-dap/mappings/adapters/cppdbg.lua
On Windows, when codelldb and cppdbg are required inside a pcall, the files silently fail to load. The configuration files for these two attempt to add members to "M.codelldb" and "M.cppdbg" respectively, but these two don't exist. The members should instead be added to the top level M table.
> fix: Fixed codelldb and cppdbg failing to setup on windows.

- lua/mason-nvim-dap/mappings/configurations.lua
Changed `console` attribute for both the python and codelldb debug adapters to use the `integratedTerminal` setting. This is a more sensible default, as without it tools like `dapui` will assume the REPL should be used - which does not allow for user input.
I have left the other adapters untouched, as I do not have a means of testing the changes right now and have only experienced the problem with Rust (CodeLLDB) and Python.
> fix: Default console settings for Python and CodeLLDB

- lua/mason-nvim-dap/init.lua
`nvim-dap` provides a vscode extension that loads in `launch.json` files. It has an internal variable for the mappings from adapters to filetypes when loading configurations. This adds automatic support to connect the filetypes to the adapters defined by `nvim-dap`
Here is the variable: https://github.com/mfussenegger/nvim-dap/blob/master/lua/dap/ext/vscode.lua#L6
And here is where they use it: https://github.com/mfussenegger/nvim-dap/blob/master/lua/dap/ext/vscode.lua#L197
> feat: automatically configure the vscode extension in `nvim-dap`

- lua/mason-nvim-dap/mappings/adapters/erlang.lua
- lua/mason-nvim-dap/mappings/filetypes.lua
- lua/mason-nvim-dap/mappings/source.lua
I added Erlang to list of adapters. DAP features like breakpoint and REPL are working.
> feat: Add erlang to list of supported debug adapters

- lua/mason-nvim-dap/mappings/configurations.lua
Add `terminalKind = "integrated"` to bashdb config. This fixes the "/dev/stdin: no such device or address" that otherwise shows up when trying to start debugging.
> fix: Update bashdb config

- lua/mason-nvim-dap/mappings/configurations.lua
V3 of Xdebug uses port 9003 by default for step debugging instead of port 9000, this updates the PHP configuration to reflect that.
> fix(php): xdebug port for PHP, resolves #140

- lua/mason-nvim-dap/mappings/configurations.lua
There are some big changes coming to Mason and this simply removes reliance on a method that is getting removed in Mason v2.
> refactor(bash): remove reliance on methods that are being deprecated

- lua/mason-nvim-dap/mappings/configurations.lua
It is unsafe to rely on paths into the `packages/` directory. I recently got a PR that adds a stable path to the `bashdb` library in Mason which allows us to use a new, stable path for this: https://github.com/mason-org/mason-registry/pull/9018
> fix(bashdb): rely on `share` directory rather than unsafe package path

- lua/mason-nvim-dap/settings.lua
This fixes (jay-babu#170) by using the `vim.fn.has` fn to check if neovim has the features of `nvim-0.11.2` or later which returns `1` if the version of neovim is `>=` `0.11.2` otherwise it returns `0` if `<` `0.11.2`. This properly checks the truthiness of the feature set by checking if the output is `1` else use the `pre-0.11.2` `vim.validate` for earlier versions of neovim. Tested on `0.11.3`
> fix: use correct fn for version check (#170)
